"""added time awre feild to blog

Revision ID: 5fee72ec4fa0
Revises: d4ece5606c0b
Create Date: 2025-08-13 13:10:12.205525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fee72ec4fa0'
down_revision: Union[str, Sequence[str], None] = 'd4ece5606c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
