"""added field to blog model

Revision ID: d4ece5606c0b
Revises: 6f8d77563766
Create Date: 2025-08-07 17:42:14.938615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ece5606c0b'
down_revision: Union[str, Sequence[str], None] = '6f8d77563766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_blogs_is_published'), 'blogs', ['is_published'], unique=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_blogs_is_published'), table_name='blogs')
    op.drop_column('blogs', 'is_published')
    # ### end Alembic commands ###
